// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkaOqoyUvQNqXkI3O706f2We9ECHs0-4k',
    appId: '1:790648716224:web:4a9bd4a2d2af147bef2625',
    messagingSenderId: '790648716224',
    projectId: 'final-year-project-faisal',
    authDomain: 'final-year-project-faisal.firebaseapp.com',
    storageBucket: 'final-year-project-faisal.firebasestorage.app',
    measurementId: 'G-ZLGEHN9R04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRmi-YCDKfI6KT5us5wmNVxGvKp6JRCoI',
    appId: '1:790648716224:android:551c25282c673858ef2625',
    messagingSenderId: '790648716224',
    projectId: 'final-year-project-faisal',
    storageBucket: 'final-year-project-faisal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJya9Rq6Z8rWDgHeLhFfJGgX-lzllQOU',
    appId: '1:790648716224:ios:f775a5d43e126caeef2625',
    messagingSenderId: '790648716224',
    projectId: 'final-year-project-faisal',
    storageBucket: 'final-year-project-faisal.firebasestorage.app',
    iosBundleId: 'com.example.fypFlutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGJya9Rq6Z8rWDgHeLhFfJGgX-lzllQOU',
    appId: '1:790648716224:ios:f775a5d43e126caeef2625',
    messagingSenderId: '790648716224',
    projectId: 'final-year-project-faisal',
    storageBucket: 'final-year-project-faisal.firebasestorage.app',
    iosBundleId: 'com.example.fypFlutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkaOqoyUvQNqXkI3O706f2We9ECHs0-4k',
    appId: '1:790648716224:web:1a2e0711908e498bef2625',
    messagingSenderId: '790648716224',
    projectId: 'final-year-project-faisal',
    authDomain: 'final-year-project-faisal.firebaseapp.com',
    storageBucket: 'final-year-project-faisal.firebasestorage.app',
    measurementId: 'G-X4B6YY6G5Q',
  );
}
